sudo: true
dist: xenial
language: minimal

stages:
  - name: build
    if: branch != master

jobs:
  include:
    - stage: build
      script: 
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/node:$TRAVIS_BRANCH .
        - docker push $DOCKER_USERNAME/node:$TRAVIS_BRANCH